---
title: "Task 1: Sierra Amphibians"
author: "Anna Talken"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
library(lubridate)
library(patchwork)
```

### Read in the data
```{r, warning=FALSE, message=FALSE}
#read in the data
amphibians <- read_excel(here("data", "sierra_amphibians.xlsx"))

amphibian_ls <- amphibians %>% 
  filter(amphibian_species == "RAMU") %>% #filter to include only mountain yellow-legged frog
  filter(amphibian_life_stage == c("SubAdult", "Tadpole", "Adult")) %>% 
  mutate(year_new = year(survey_date))  %>%  #created new column with only year
  group_by(year_new, amphibian_life_stage) %>%  #count number of frogs by year and life stage
  summarize(frog_count = sum(amphibian_number, na.rm = TRUE))

```

### Graph #1 Code: Comparing Mountain Yellow-Legged Frog populations by life stage
```{r, warning=FALSE, message=FALSE}
#create ggplot
graph1 <- ggplot(data = amphibian_ls, aes(x = year_new, y = frog_count, color = amphibian_life_stage)) +
  geom_point() +
  geom_line() +
  theme_minimal() +
  labs(title = "Mountain Yellow-Legged Frog Population from 1995 to 2002",
       x = "Year",
       y= "Number",
       color = "Life Stage") +
  facet_wrap(~amphibian_life_stage) +
  theme(legend.position = "none")
```

### Graph #2 Code: Top 5 Lakes with Mountain Yellow-Legged Frogs

```{r, warning=FALSE, message=FALSE}

amphibians$lake_id <-as.character(as.numeric(amphibians$lake_id))


amphibian_top5 <- amphibians %>% 
  filter(amphibian_life_stage %in% c("SubAdult", "Adult")) %>% #filter to include only Adult and SubAdult frogs
  filter(amphibian_location == "in lake") %>% #only include frogs in the lake
  filter(amphibian_species == "RAMU") %>% 
  group_by(lake_id) %>% 
  summarize(ramu_frogs = sum(amphibian_number)) %>%  #total frog counts per each lake
  mutate(lake_id = fct_reorder(lake_id, ramu_frogs)) %>% #arrange in descending order
  slice_max(ramu_frogs, n=5) #keep top 5 highest values of frogs per lake
  
# create ggplot
graph2 <- ggplot(data= amphibian_top5, aes(x=reorder(lake_id, -ramu_frogs), y=ramu_frogs)) +
  geom_col(fill = "cyan4") +
  labs(title = "Top 5 lakes with the greatest number of Mountain Yellow-Legged Frogs", 
       x= "Lake ID",
       y = "Number") +
  theme_minimal() +
  coord_flip()

```
### Combine graphs using 'patchwork' package

```{r, warning=FALSE, message=FALSE, fig.cap= "Figure 1. Top: The change in Mountain Yellow-Legged Frog populations from 1995 to 2002 for different life stages - adults, subadults and tadpoles. Bottom: The top 5 lakes with the highest number of Mountain Yellow-Legged Frogs."}
graph1 / graph2 #combining graph 1 and graph 2 on the same figure

```
























